batch_size: 256
commit_hash: 929ae53
data_dir: data/IA/NeuralHydrology
dataset: generic
device: cpu
dynamic_inputs:
- precipitation
epochs: 50
experiment_name: satellite_water_level_test
head: regression
hidden_size: 128
img_log_dir: 
  /home/sar_hydro/STUDIES/EtudesEB/PythonProject/runs/satellite_water_level_test_1604_192156/img_log
initial_forget_bias: 3
learning_rate:
  0: 0.001
  30: 0.0001
loss: NSE
max_updates_per_epoch: 500
metrics:
- NSE
- KGE
model: cudalstm
number_of_basins: 196
optimizer: AdamW
output_dropout: 0.4
package_version: 1.13.0
predict_last_n: 1
run_dir: 
  /home/sar_hydro/STUDIES/EtudesEB/PythonProject/runs/satellite_water_level_test_1604_192156
save_validation_results: true
seed: 455547
seq_length: 365
static_attributes:
- aire_km2
- frac_urban
- frac_forest
- frac_agriculture
- sg_clay_0_30cm
- sg_sand_0_30cm
- sg_silt_0_30cm
target_variables:
- water_level
test_basin_file: AI/LSTM/NeuralHydro/val_basins.txt
train_basin_file: AI/LSTM/NeuralHydro/train_basins.txt
train_dir: 
  /home/sar_hydro/STUDIES/EtudesEB/PythonProject/runs/satellite_water_level_test_1604_192156/train_data
train_end_date: 31/12/2023
train_start_date: 01/01/2016
validate_every: 5
validate_n_random_basins: 40
validation_basin_file: AI/LSTM/NeuralHydro/val_basins.txt
validation_end_date: 31/12/2025
validation_start_date: 01/01/2024
