batch_size: 256
commit_hash: 929ae53
data_dir: data/IA/NeuralHydrology
dataset: generic
device: cpu
dynamic_inputs:
- precipitation
- temperature
- pet
epochs: 50
experiment_name: satellite_water_level_test
head: regression
hidden_size: 64
img_log_dir: 
  /home/sar_hydro/STUDIES/EtudesEB/PythonProject/runs/satellite_water_level_test_1504_165125/img_log
learning_rate:
  0: 0.001
  30: 0.0001
loss: NSE
metrics:
- NSE
- KGE
model: cudalstm
number_of_basins: 117
optimizer: Adam
output_dropout: 0.4
package_version: 1.13.0
predict_last_n: 1
run_dir: 
  /home/sar_hydro/STUDIES/EtudesEB/PythonProject/runs/satellite_water_level_test_1504_165125
save_validation_results: true
seed: 999890
seq_length: 365
static_attributes:
- aire_km2
- frac_urban
- frac_forest
- frac_wetland
- sg_clay_0_30cm
- sg_sand_0_30cm
- sg_silt_0_30cm
target_variables:
- water_level
test_basin_file: AI/LSTM/NeuralHydro/val_basins.txt
train_basin_file: AI/LSTM/NeuralHydro/train_basins.txt
train_dir: 
  /home/sar_hydro/STUDIES/EtudesEB/PythonProject/runs/satellite_water_level_test_1504_165125/train_data
train_end_date: 31/12/2020
train_start_date: 01/01/2016
validate_every: 5
validate_n_random_basins: 3
validation_basin_file: AI/LSTM/NeuralHydro/val_basins.txt
validation_end_date: 31/12/2021
validation_start_date: 01/01/2021
