# ═══════════════════════════════════════════════
# EXPERIMENT
# ═══════════════════════════════════════════════
experiment_name: arlstm_Alti_modele2

# ═══════════════════════════════════════════════
# DATASET
# ═══════════════════════════════════════════════
dataset: generic
data_dir: ./data/IA/NeuralHydrology_satellite/
train_basin_file: ./AI/LSTM/NeuralHydro_satellite/train_basins.txt
validation_basin_file: ./AI/LSTM/NeuralHydro_satellite/train_basins.txt
test_basin_file: ./AI/LSTM/NeuralHydro_satellite/val_basins.txt

# ═══════════════════════════════════════════════
# PÉRIODES
# ═══════════════════════════════════════════════
train_start_date: "01/01/2016"
train_end_date: "31/12/2023"
validation_start_date: "09/01/2024"
validation_end_date: "31/12/2025"

# ═══════════════════════════════════════════════
# VARIABLES
# ═══════════════════════════════════════════════
target_variables:
  - water_level

# lag-1 dans ce dataset = 10 jours réels (1 point tous les 10j)
lagged_features:
  water_level:
    - 1    # lag-10j réels
#    - 2    # lag-20j réels
#    - 3    # lag-30j réels
autoregressive_inputs:
  - water_level_shift1


# Modèle 2 — J0 + moyennes J3 + moyennes J10
dynamic_inputs:
  - precipitation_J0
  - temperature_J0
  - pet_J0
  - precip_mean_J3
  - pet_mean_J3
  - temp_mean_J3
  - precip_mean_J10
  - pet_mean_J10
  - temp_mean_J10
  - clim_mean_20j
  - clim_std_20j
#  - water_level_shift2  # ← manque
#  - water_level_shift3

static_attributes:
  - aire_km2
  - lon
  - lat
  - frac_urban
  - frac_forest
  - frac_agriculture
  - sg_clay_0_30cm
  - sg_sand_0_30cm
  - sg_silt_0_30cm
  - strahler
  - elevation_mean
  - slope_mean


# ═══════════════════════════════════════════════
# ARCHITECTURE
# ═══════════════════════════════════════════════
model: arlstm
head: regression
hidden_size: 128
seq_length: 36
predict_last_n: 1

# ═══════════════════════════════════════════════
# ENTRAÎNEMENT
# ═══════════════════════════════════════════════

batch_size: 256
output_dropout: 0.3
optimizer: AdamW
learning_rate:
  0: 0.0003              # réduire AVANT la dégradation
  10: 0.0001
epochs: 15

loss: NSE

initial_forget_bias: 3
save_validation_results: True
# Moins de updates car séries plus courtes (36 pts/an vs 365)
max_updates_per_epoch: 4000

# ═══════════════════════════════════════════════
# VALIDATION
# ═══════════════════════════════════════════════
validate_every: 2
validate_n_random_basins: 800
metrics:
  - NSE
  - KGE

# ═══════════════════════════════════════════════
# DEVICE
# ═══════════════════════════════════════════════
device: cpu