attribute_means:
  aire_km2: 1386.2647959183676
attribute_stds:
  aire_km2: 4927.897416008478
xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    pet:
      dims: []
      attrs: {}
      data: 4.101778507232666
    precipitation:
      dims: []
      attrs: {}
      data: 5.097757816314697
    temperature:
      dims: []
      attrs: {}
      data: 6.944552898406982
    water_level:
      dims: []
      attrs: {}
      data: 0.9903464913368225
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    pet:
      dims: []
      attrs: {}
      data: 4.848366737365723
    precipitation:
      dims: []
      attrs: {}
      data: 2.808157444000244
    temperature:
      dims: []
      attrs: {}
      data: 11.258986473083496
    water_level:
      dims: []
      attrs: {}
      data: -0.0386384055018425
