# ═══════════════════════════════════════════════
# EXPERIMENT
# ═══════════════════════════════════════════════
experiment_name: arlstm_DtoD96_quantile

# ═══════════════════════════════════════════════
# DATASET
# ═══════════════════════════════════════════════
dataset: generic
data_dir: ./data/IA/NeuralHydroDtoD96
train_basin_file: ./AI/LSTM/NeuralHydroDtoD96/train_basins.txt
validation_basin_file: ./AI/LSTM/NeuralHydroDtoD96/val_basins.txt

# ═══════════════════════════════════════════════
# PÉRIODES
# ═══════════════════════════════════════════════
train_start_date: "01/01/2016"
train_end_date: "31/12/2025"
validation_start_date: "01/01/2016"
validation_end_date: "31/12/2025"

# ═══════════════════════════════════════════════
# VARIABLES
# ═══════════════════════════════════════════════
num_workers: 4
cache_validation_data: True

dynamics_embedding:
  type: fc
  hiddens:
    - 30
    - 20
  activation: tanh
  dropout: 0.2

target_variables:
  - water_level

lagged_features:
  water_level:
    - 1

use_frequencies:
  - 1D

autoregressive_inputs:
  - water_level_shift1

dynamic_inputs:
  - precipitation_J0
  - temperature_J0
  - pet_J0
  - precip_mean_J3
  - temp_mean_J3
  - pet_mean_J3
  - precip_mean_J10
  - temp_mean_J10
  - pet_mean_J10
  - precip_max_J10
  - precip_last7
  - nb_jours_pluie_J10
  - snow_depth_J0
  - snowmelt_J0
  - snow_depth_mean_J3
  - snowmelt_mean_J3
  - snow_depth_mean_J10
  - snowmelt_mean_J10
  - clim_mean_20j
  - clim_std_20j
  - doy_sin
  - doy_cos

static_attributes:
  - aire_km2
  - lon
  - lat
  - frac_urban
  - frac_forest
  - frac_agriculture
  - sg_clay_0_30cm
  - sg_sand_0_30cm
  - sg_silt_0_30cm
  - strahler
  - elevation_mean
  - slope_mean

# ═══════════════════════════════════════════════
# ARCHITECTURE
# ═══════════════════════════════════════════════
model: arlstm
head: quantileregression
hidden_size: 256
seq_length:
  1D: 365
predict_last_n:
  1D: 1

# ═══════════════════════════════════════════════
# ENTRAÎNEMENT
# ═══════════════════════════════════════════════
batch_size: 64
output_dropout: 0.4
clip_gradient_norm: 0.8
target_noise_std: 0.01
optimizer: AdamW
learning_rate:
  0: 0.0008
  12: 0.0004
  20: 0.0002

epochs: 30
loss: MultiQuantileLoss
quantiles: [0.05, 0.25, 0.50, 0.75, 0.95]
initial_forget_bias: 3
save_validation_results: True
max_updates_per_epoch: 1600

# ═══════════════════════════════════════════════
# VALIDATION
# ═══════════════════════════════════════════════
validate_every: 1
validate_n_random_basins: 400
metrics:
  - NSE
  - KGE
  - FHV

# ═══════════════════════════════════════════════
# DEVICE
# ═══════════════════════════════════════════════
device: cpu