# ═══════════════════════════════════════════════
# EXPERIMENT
# ═══════════════════════════════════════════════
experiment_name: arlstm_feat27jHigh_modele2
# ═══════════════════════════════════════════════
# DATASET
# ═══════════════════════════════════════════════
dataset: generic
data_dir: ./data/IA/NeuralHydrology_feat27j
train_basin_file: ./AI/LSTM/NeuralHydro_feat27j_high/train_basins.txt
validation_basin_file: ./AI/LSTM/NeuralHydro_satellite_27D/stations_27j.txt
test_basin_file: ./AI/LSTM/NeuralHydro_feat27j_low/val_basins.txt

# ═══════════════════════════════════════════════
# PÉRIODES
# ═══════════════════════════════════════════════
train_start_date: "01/01/2016"
train_end_date: "31/12/2025"
validation_start_date: "01/01/2016"
validation_end_date: "31/12/2025"

# ═══════════════════════════════════════════════
# VARIABLES
# ═══════════════════════════════════════════════
num_workers: 4
cache_validation_data: True

#statics_embedding:
#  type: fc
#  hiddens:
#    - 30
#    - 20
#  activation: tanh
#  dropout: 0.0

dynamics_embedding:
  type: fc
  hiddens:
    - 30
    - 20
  activation: tanh
  dropout: 0.2

target_variables:
  - water_level

# lag-1 dans ce dataset = 10 jours réels (1 point tous les 10j)
lagged_features:
  water_level:
    - 1    # lag-10j réels
#    - 2    # lag-20j réels
#    - 3    # lag-30j réels
use_frequencies:
  - 27D
autoregressive_inputs:
  - water_level_shift1


# Modèle 2 — J0 + moyennes J3 + moyennes J10
dynamic_inputs:
  - precipitation_J0
  - temperature_J0
  - pet_J0
  - precip_mean_J3
  - pet_mean_J3
  - temp_mean_J3
  - precip_mean_J27
  - precip_mean_J10
#  - pet_mean_J10
  - temp_mean_J10
#  - snow_depth_J0
#  - snowmelt_J0
#  - snow_depth_mean_J3
#  - snowmelt_mean_J3
#  - snow_depth_mean_J10
#  - snowmelt_mean_J10
#  - clim_mean
#  - clim_std
  - clim_mean_20j
  - clim_std_20j
  - precip_max_J27
  - precip_last7
  - nb_jours_pluie_J27
  - precip_mean_J14
#  - doy_sin
#  - doy_cos
#  - water_level_shift2  # ← manque
#  - water_level_shift3

static_attributes:
  - aire_km2
  - lon
  - lat
  - frac_urban
  - frac_forest
  - frac_agriculture
  - sg_clay_0_30cm
  - sg_sand_0_30cm
  - sg_silt_0_30cm
  - strahler
  - elevation_mean
  - slope_mean


# ═══════════════════════════════════════════════
# ARCHITECTURE
# ═══════════════════════════════════════════════
model: arlstm
head: regression
hidden_size: 256
seq_length:
  27D: 20
predict_last_n:
  27D: 1

# ═══════════════════════════════════════════════
# ENTRAÎNEMENT
# ═══════════════════════════════════════════════

batch_size: 64
output_dropout: 0.4
clip_gradient_norm: 0.8
target_noise_std: 0.01
optimizer: AdamW
learning_rate:
  0: 0.0006
  12: 0.0003
  20: 0.0001

epochs: 30

loss: NSE

initial_forget_bias: 3
save_validation_results: True
# Moins de updates car séries plus courtes (36 pts/an vs 365)
max_updates_per_epoch: 20000

# ═══════════════════════════════════════════════
# VALIDATION
# ═══════════════════════════════════════════════
validate_every: 1
validate_n_random_basins: 2000
metrics:
  - NSE
  - KGE

# ═══════════════════════════════════════════════
# DEVICE
# ═══════════════════════════════════════════════
device: cpu